### ISSUE TITLE
Same key item xml

### ISSUE THREAD

**Issue by arthurkirkosa** [spatie/array-to-xml#10]
What format must my array be to have as xml
```xml
<Flights>
    <Flight>
        <FlightId>123</FlightId>
        ...
    </Flight>
    <Flight>
        ...
    </Flight>
</Flights>
```

**Comment by fancenl** [comment]
This is not possible out of the box, because PHP-arrays cannot have the same key's.

**Comment by arthurkirkosa** [comment]
Doing something like this did the trick.

```
ArrayToXml::convert([
    'Flight' => [
        ['id' => 1, '...' => '...'],
        ['id' => 2, '...' => '...'],
        [...],
    ],
], 'Flights');
```

**Comment by WouterWidgets** [comment]
I know this issue has been closed, but for anyone who is struggling with adding attributes to same-key items, here's a detailed example:

```
$data = [
    '_attributes' => ['foo' => true, 'bar' => 123, 'name' => 'something'],
    'Param' => [
        [
            ['_attributes' => ['name' => 'test1']],
            'This is the node content for test 1'
        ],
        [
            ['_attributes' => ['name' => 'test2']],
            'This is the node content for test 2'
        ],
        [
            ['_attributes' => ['name' => 'test3']],
            'This is the node content for test 3'
        ]
    ]
];

echo ArrayToXml::convert($data, 'Params');
```

This will output something like:

```
<Params foo="true" bar="123" name="something">
    <Param name="test1">This is the content for test 1</Param>
    <Param name="test2">This is the content for test 2</Param>
    <Param name="test3">This is the content for test 3</Param>
</Params>
```

**Comment by ruskid** [comment]
@WouterWidgets this works, but "This is the content for test 1" can't be cdata =)

**Comment by prathamesh-khadakban** [comment]
@ruskid  Hi Victor,
will you please share your foreach logic for add _cdata for node.
Thank you.

**Comment by josem1992** [comment]
issue if the array has objects as well , this returns json in the elements 

      $length = count($Cantidad);

      $LineaDetalle = array();
      $linea = null;
      for($i=0;$i<$length;$i++){

          $linea = new FacturaLinea();
          $linea->Cantidad = $Cantidad[$i];
          $linea->UnidadMedida = $UnidadMedida[$i];
          $linea->DetalleMerc = $DetalleMerc[$i];
          $linea->PrecioUnitario = $PrecioUnitario[$i];
          $linea->MontoTotal = $MontoTotal[$i];
          $linea->MontoDescuento = $MontoDescuento[$i];
          $linea->SubTotal = $SubTotal[$i];
        array_push($LineaDetalle,$linea);
      }
      $Detalle = ['Linea'=>$LineaDetalle];
      return $Detalle;

**Comment by erkanrua** [comment]
I have same problem with arthurkirkosa , I aggree array has just one key but some xml export files has many same nodes like site maps. For example 
<sitemapindex>
<sitemap>
<loc>url1</loc>
<lastmod>2019-03-21T15:02:24+03:00</lastmod>
</sitemap>
<sitemap>
<loc>url2</loc>
<lastmod>2019-03-21T15:02:24+03:00</lastmod>
</sitemap>
<sitemap>
<loc>url3</loc>
<lastmod>2019-03-21T15:02:24+03:00</lastmod>
</sitemap>
</sitemapindex>
So we don't create same sitemap nodes your class so we need to solve this problem.
