### ISSUE TITLE
Add formatOutput parameter

### ISSUE THREAD

**Issue by pulponair** [spatie/array-to-xml#102]
Add the abillity to toggle doms "formatOutput" Parameter for 
1. Better Readbillity
2. Some xml importers e.g. the one of Shopware does not accept unformated xml (diva!).

Even better, add and addional array for Dom Paramters to the constructor for more fleixbility.

**Comment by freekmurze** [comment]
Feel free to PR features. Be sure to included tests and an updated readme.
