### ISSUE TITLE
How to close element if value not exist like <tf_prev1GivenName/> instead of <tf_prev1GivenName></tf_prev1GivenName>

### ISSUE THREAD

**Issue by hiren004** [spatie/array-to-xml#108]
Hi there,

First of all thanks for this package, it's awesome! 

I've implemented it in my project and working fine for now. But I just want to know that is there any way to close the tag/element like `<tf_prev1GivenName/>` if there's no value instead of `<tf_prev1GivenName></tf_prev1GivenName>`??

If yes then please let me know so that I can move further as it pains me from 2 days!!!

Thank you!

**Comment by pulponair** [comment]
@hiren004 
Actually Domdocument:saveXML() should do that automatically unless you provide the   LIBXML_NOEMPTYTAG  option.

But unfortunatly that is not working for array-to-xml atm since setting a node value to an empty string ('')  technically adds an empty textnode to the document which can't be optimized to a selfclosing tag.

To change that one can check for and empty string here:
https://github.com/spatie/array-to-xml/blob/master/src/ArrayToXml.php#L108

And don't not set the value if  `$value === ''`. 

That is actually easy to fix but will break the default behavior of XmlToArray.

**Comment by jeremycurny** [comment]
@hiren004 you can patch the package with this other package: https://github.com/cweagans/composer-patches

Have a look to my PR. Using null as value will allow you to self-close element.
Here is the patch:

```
--- a/src/ArrayToXml.php
+++ b/src/ArrayToXml.php
@@ -100,6 +100,10 @@ class ArrayToXml
     {
         $sequential = $this->isArrayAllKeySequential($value);
 
+        if ($value === null) {
+            return;
+        }
+
         if (! is_array($value)) {
             $value = htmlspecialchars($value);

```

**Comment by hiren004** [comment]
@jeremycurny, thanks for the info!

But I don't want to use another one package as I already use this one. Anyway, thanks for the suggestion!

**Comment by hiren004** [comment]
@pulponair ,

Thanks for your reply! Currently, I'm using this way to achieve the self-closing element:

`'sf_previousnamedetails' => [
              'tf_prev1GivenName'    => $passportApplication['applicant_details']['previous_first_name1'] ? $passportApplication['applicant_details']['previous_first_name1'].' '.$passportApplication['applicant_details']['previous_middle_name1'] : ''
],` 
But not working for the self closing element. Do you have any idea what was the issue in my code?

Thanks mate!

**Comment by pulponair** [comment]
Hi,
> But not working for the self-closi
As already mentioned. xmlToArray is not capable of selfclosing tags cause it adds an empty value which  results in an empty xml textnode between the opening and the closing tag so Domdocument->saveXML won't generate a selfclosing tag.

If you need that go for the route @eremycurny c suggested. It is not another package its just a composer package that allows you to patch other packages. It works pretty well i use it quite often. All you have to to is requiere that package, provide it with the patch and fire composer install. 

Thats it.

**Comment by mtracz** [comment]
If someone still has problem with self-closing element, just pass empty array as value. (Tested on v2.11.2)

```
$result = ArrayToXml::convert(
    [
        "test" => 123,
        "empty" => [],
        "null" => null,
        "false" => false,
        "true" => true,
        "zero" => 0,
        "emptyString" => "",
        "nested" => [
            "some" => 777,
            "empty" => [],
        ],
        "withAttributeOnly" => [
            "@attributes" => [
                "id" => "some_atribute",
                ],
        ],
        "withAttributeAndValue" => [
            "@attributes" => [
                "id" => "some_atribute",
            ],
            "@value" => "some_value",
        ],
    ],
    [
        "rootElementName" => "root",
    ],
);
```

Result:
```
<?xml version="1.0"?>
<root>
	<test>123</test>
	<empty/>
	<null></null>
	<false></false>
	<true>1</true>
	<zero>0</zero>
	<emptyString></emptyString>
	<nested>
		<some>777</some>
		<empty/>
	</nested>
	<withAttributeOnly id="some_atribute"/>
	<withAttributeAndValue id="some_atribute">some_value</withAttributeAndValue>
</root>
```

**Comment by davideperi** [comment]
If you have an attribute the array [] workaround does not work:

For example:

```
$array = [
    'Good guy' => [
        'name' => 'Luke Skywalker',
        'weapon' => 'Lightsaber'
    ],
    'Bad guy' => [
        'name' => 'Sauron',
        'weapon' => 'Evil Eye'
    ],
	'exmaple' => [
		[
	        '_value' => [],
	        '_attributes' => [
	            'text' => "A"
	        ],
	        'example' => [
	            '_value' => [],
	            '_attributes' => [
	                'text' => "B"
	            ]
	        ]
	    ]
	]
];


$result = ArrayToXml::convert(
            $array, 
            [
                'rootElementName' => 'rss',
                '_attributes' => [
                    'xmlns:itunes'=> "http://www.itunes.com/dtds/podcast-1.0.dtd",
                    'xml:lang'=> "en",
                    'version'=> "2.0",
                    'xmlns:atom' => "http://www.w3.org/2005/Atom"
                ]
            ],
            "false", 
            "utf-8",
            "1.0",
            ['formatOutput' => true]
        );

echo($result);
```


Produce



```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang="en" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <Good_guy>
    <name>Luke Skywalker</name>
    <weapon>Lightsaber</weapon>
  </Good_guy>
  <Bad_guy>
    <name>Sauron</name>
    <weapon>Evil Eye</weapon>
  </Bad_guy>
  <itunes:category text="A">
    <_value/>
    <itunes:category text="B">
      <_value/>
    </itunes:category>
  </itunes:category>
</rss>

```

**Comment by davideperi** [comment]
This workaround does not work if you have attribute inside the self close tag.

For example:

```
$array = [
	'categoryA' => [],
    'categoryB' => [
	    '_value' => '',
	    '_attributes' => [
	        'text' => 'Society &amp; Culture'
	    ],
	    'itunes:category' => [
	        '_value' => [],
	        '_attributes' => [
	            'text' => 'Documentary'
	        ]
	    ]
	]
];


$result = ArrayToXml::convert(
            $array, 
            [
                'rootElementName' => 'rss',
                '_attributes' => [
                    'xmlns:itunes'=> "http://www.itunes.com/dtds/podcast-1.0.dtd",
                    'xml:lang'=> "en",
                    'version'=> "2.0",
                    'xmlns:atom' => "http://www.w3.org/2005/Atom"
                ]
            ],
            "false", 
            "utf-8",
            "1.0",
            ['formatOutput' => true]
        );

echo($result);
```


Produces:


```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang="en" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <categoryA/>
  <categoryB text="Society &amp;amp; Culture">
  	<itunes:category text="Documentary"><_value/></itunes:category>
  </categoryB>
</rss>
```

instead of

```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang="en" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <categoryA/>
  <categoryB text="Society &amp;amp; Culture">
  	<itunes:category text="Documentary" />
  </categoryB>
</rss>
```
