### ISSUE TITLE
I don't want '<?xml version="1.0"?>' what to do

### ISSUE THREAD

**Issue by RajuTicvic** [spatie/array-to-xml#110]
<?xml version="1.0"?>

how to removed or disable this line

**Comment by vdbelt** [comment]
You could do something like this:

```
$result = (new ArrayToXml($array))->toDom();

foreach($result->childNodes as $node) {
    print $result->saveXML($node);
}
```

**Comment by RajuTicvic** [comment]
@vdbelt
no no,
i want to remove only the xml tag line
and one more added to the xml <test xmlns="http://www.test.com/test"></test> in intermediate

i need like this 
![Capture123](https://user-images.githubusercontent.com/47621807/61047523-5636dc00-a3fd-11e9-94be-600217c026d5.PNG)

**Comment by emabusi** [comment]
@RajuTicvic did you get a solution?

**Comment by robertnicjoo** [comment]
You can define headings like this and it removes that line for you

```php
$result = ArrayToXml::convert($array, [
  'rootElementName' => 'NMEXML',
  '_attributes' => [
    'EximID'=> "12551",
    'BranchCode'=> '1524445,
    'ACCOUNTANTCOPYID'=> ""
  ]
]);
```

**Comment by NeftaliAcosta** [comment]
> how to removed or disable this line

Could you fix it?
