### ISSUE TITLE
Bugreport for:   ArrayToXml::convert(['a' => ['0', '1']]);

### ISSUE THREAD

**Issue by petrich** [spatie/array-to-xml#111]
Hi there, great Work +1 .. Thank you!

Just a small bug report:

```php
echo ArrayToXml::convert(['a' => ['0', '1']]);
```
current result:
`<root><a>1</a></root>`

expected:
`<root><a>0</a><a>1</a></root>`

Would be great this could be fixed.

Thank you very much.

**Comment by freekmurze** [comment]
This has been fixed in the latest version.

**Comment by petrich** [comment]
@freekmurze 
Thank you for fixing. Above example works now. :+1: 

But...

```php
echo ArrayToXml::convert(['a' => ['', '1']]);
```
current result:
`<root><a>1</a></root>`

expected:
`<root><a></a><a>1</a></root>`

Is there a fix possible?

Thank you again.
