### ISSUE TITLE
how to add more than one line from the same node?

### ISSUE THREAD

**Issue by EloneSampaio** [spatie/array-to-xml#132]
**I need to create an xml with several lines of an invoice, but when I add more than one line of products in the array at the output of the file, only one line appears. how to solve this?**

**Comment by samrollin1** [comment]
I have the same issue, is it an issue or is there documentation missing?

**Comment by samrollin1** [comment]
You need to add the field and then nest arrays into it so the field is repeated.

Example to repeat the "field" twice inside of the 'add' property

`
'add' => [
                    'field' => [
                      [
                        '_attributes' => ['name' => 'Employee'],
                        'value' => $request->email,
                      ],
                      [
                        '_attributes' => ['name' => 'Refund_Request'],
                        'value' => $request->amount,
                      ],
                    ]
                  ]
`

In this case it will output : 
<add>
  <field name="Employee">
    <value>whatever@gmail.com</value>
  </field>
  <field name="Refund_Request">
    <value>34.00</value>
  </field>
</add>

Hope this helps

**Comment by samrollin1** [comment]
> **I need to create an xml with several lines of an invoice, but when I add more than one line of products in the array at the output of the file, only one line appears. how to solve this?**

You need to add the field and then nest arrays into it so the field is repeated.

Example to repeat the "field" twice inside of the 'add' property

`
'add' => [
                    'field' => [
                      [
                        '_attributes' => ['name' => 'Employee'],
                        'value' => $request->email,
                      ],
                      [
                        '_attributes' => ['name' => 'Refund_Request'],
                        'value' => $request->amount,
                      ],
                    ]
                  ]
`

In this case it will output : 
`
<add>
  <field name="Employee">
    <value>whatever@gmail.com</value>
  </field>
  <field name="Refund_Request">
    <value>34.00</value>
  </field>
</add>
`

Hope this helps

**Comment by EloneSampaio** [comment]
Thanks @samrollin1
