### ISSUE TITLE
howto change encoding 

### ISSUE THREAD

**Issue by fap2this1** [spatie/array-to-xml#14]
Hi

is it possible to set an encoding when converting array . like this  

<?xml version="1.0" encoding="UTF-8"?>

**Comment by freekmurze** [comment]
Not sure what you mean, but I accept simple, well tested PRs that add functionality to the package.

**Comment by fap2this1** [comment]
Hi!

When i try the following:

use Spatie\ArrayToXml\ArrayToXml;
...
$array = [
    'Good guy' => [
        'name' => 'Luke Skywalker',
        'weapon' => 'Lightsaber'
    ],
    'Bad guy' => [
        'name' => 'Sauron',
        'weapon' => 'Evil Eye'
    ]
];

$result = ArrayToXml::convert($array);

result is : 

<?xml version="1.0"?>

what I want is encoding=utf-8. Like this:

<?xml version="1.0" encoding="UTF-8"?>

**Comment by Gemorroj** [comment]
@fap2this1 i use this code:
```php
        $dom = (new ArrayToXml($array, 'Document'))->toDom();
        $dom->encoding = 'UTF-8';
```

**Comment by fap2this1** [comment]
Thanks!
