### ISSUE TITLE
Option to remove XML tag in output

### ISSUE THREAD

**Issue by Abuelodelanada** [spatie/array-to-xml#144]
When using this library to build XML to perform a SOAP request would be very useful having a way to remove the `<?xml version="1.0"?>` tag. 
May be using [`LIBXML_NOXMLDECL`](https://www.php.net/manual/en/libxml.constants.php) ?

**Comment by Dartui** [comment]
It can be easily achieved with this code:
```php
$xml = ArrayToXml::convert('...');

$dom = new DOMDocument();
$dom->loadXml($xml);

$xml = $dom->saveXML($dom->documentElement);
```

Source: https://stackoverflow.com/questions/5947695/remove-xml-version-tag-when-a-xml-is-created-in-php

**Comment by Abuelodelanada** [comment]
Nice solution @Dartui !

Thank you very much!
