### ISSUE TITLE
could you please  support chinese words?

### ISSUE THREAD

**Issue by jonny77** [spatie/array-to-xml#146]
$data = [
            'Good guy' => [
                '_attributes' => ['attr1' => '中文'],
                'name' => 'Luke Skywalker',
                'weapon' => 'Lightsaber'
            ],
            'Bad guy' => [
                'name' => 'Sauron',
                'weapon' => 'Evil Eye'
            ],
            'The survivor' => [
                '_attributes' => ['house'=>'Hogwarts'],
                '_value' => 'Harry Potter'
            ]
        ];

the result:   <Good_guy attr1="s&#x4E3D;&#x6C34;&#x4E3D;&#x6C34;">

**Comment by freekmurze** [comment]
Feel free to PR improvements
