### ISSUE TITLE
Incorrect value for integer

### ISSUE THREAD

**Issue by Fulcanellii** [spatie/array-to-xml#157]
Incorrect display value for integer

``` 
$xml = [ exampleKey' => [
    '_attributes' => ['attr' => 'Lorem'],
    '_value' => 500,
    ]
];
```
![image](https://user-images.githubusercontent.com/54025480/108988183-5eb95480-76be-11eb-9e78-b5e50b0dd6fe.png)

If put number in qoutes, displayed correctly

``` 
$xml = [ exampleKey' => [
    '_attributes' => ['attr' => 'Lorem'],
    '_value' => '500',
    ]
];
```

![image](https://user-images.githubusercontent.com/54025480/108988464-b1930c00-76be-11eb-9d45-d7521e046975.png)

P.S The problem was solved with "strval"

**Comment by freekmurze** [comment]
Feel free to submit a PR that fixes this for you, make sure to include a test.
