### ISSUE TITLE
Invalid Character Error

### ISSUE THREAD

**Issue by aleksandrzhiliaev** [spatie/array-to-xml#16]
I am trying to convert this to xml and get `Invalid Character Error`:

```
Array
(
    [0] => Array
        (
            [from] => PMUSD
            [to] => OKUSD
            [in] => 1.03514
            [out] => 1
            [amount] => 99572.17
            [minamount] => 3 USD
            [param] => auto
        )

    [1] => Array
        (
            [from] => PMUSD
            [to] => YAMRUB
            [in] => 1
            [out] => 58.77
            [amount] => 13637.23
            [minamount] => 5 USD
            [param] => auto
        )
)
```

**Comment by freekmurze** [comment]
Do you know which field is causing troubles? Toy a little bit with the input and let me know which characters are causing problems.

**Comment by AEK-BKF** [comment]
The problem is you set a number as node, 
Add '_' to numbers like this :
Array
(
    '_0' => Array
        (
            [from] => PMUSD
            [to] => OKUSD
            [in] => 1.03514
            [out] => 1
            [amount] => 99572.17
            [minamount] => 3 USD
            [param] => auto
        )

    '_1' => Array
        (
            [from] => PMUSD
            [to] => YAMRUB
            [in] => 1
            [out] => 58.77
            [amount] => 13637.23
            [minamount] => 5 USD
            [param] => auto
        )
)

**Comment by aleksandrzhiliaev** [comment]
But the problem here that your library doesn't understand arrays?
so if I add like this:
```
$data[] = ['key1'=>'value1'];
$data[] = ['key2'=>'value2'];
```

**Comment by njenga55** [comment]
did anybody  manage to fix this, i need this solution for a project am working on. 
am using array_push() to create my array so i have no control of the indexes since my array has child element to a 4th dimension.

**Comment by mithun3010** [comment]
Just enclose the array within a key like this. It should work.

```
Array
(
    [test] => Array
            (
                [0] => Array
                    (
                        [from] => PMUSD
                        [to] => OKUSD
                        [in] => 1.03514
                        [out] => 1
                        [amount] => 99572.17
                        [minamount] => 3 USD
                        [param] => auto
                    )

                [1] => Array
                    (
                        [from] => PMUSD
                        [to] => YAMRUB
                        [in] => 1
                        [out] => 58.77
                        [amount] => 13637.23
                        [minamount] => 5 USD
                        [param] => auto
                    )
            )       
)
```
