### ISSUE TITLE
feature: Support dashes too

### ISSUE THREAD

**Issue by bkmorse** [spatie/array-to-xml#163]
When generating the xml from an array, any index that has a space in it, gets replaced by an underscore.

For example: favorite color would convert to <favorite_color></favorite_color>

It would be nice to be able to set it to use dashes instead: <favorite-color></favorite-color>

**Comment by freekmurze** [comment]
Feel free to PR this (with tests and an updated readme).

**Comment by patinthehat** [comment]
@freekmurze I'm working on a PR for this feature now.
