### ISSUE TITLE
Allow null to be present in XML

### ISSUE THREAD

**Issue by tsuzukit** [spatie/array-to-xml#169]
since Release 3.0.0, null is not allowed to be present in array.
For example, below array is converted to xml without error in 2.16.0, but in 3.0.0...

```
$arr = [
    'test' => null',
];

ArrayToXml::convert($arr);
```

Error is raised because `isArrayAllKeySequential` only takes `array` or `string`.
I wonder if it can be modified such that `null` is accepted for this method.

Thanx in advance!

**Comment by freekmurze** [comment]
Feel free to send a PR with tests for this 👍
