### ISSUE TITLE
Add Encoding="UTF-8" with version

### ISSUE THREAD

**Issue by AEK-BKF** [spatie/array-to-xml#17]
Hi,

Please could you add Encoding="UTF-8" in the head of xml file ? thanks.

**Comment by freekmurze** [comment]
Send a PR and I'll merge it in.

**Comment by kamrava** [comment]
@freekmurze 
I've sent a PR. I don't know why always StyleCI fails my PRs :( 
(If you know tell me please.)

**Comment by kamrava** [comment]
Here is the [PR](https://github.com/spatie/array-to-xml/pull/20)
