### ISSUE TITLE
Sequential node with namespace throws DOMException with Namespace Error message

### ISSUE THREAD

**Issue by vaclavvanik** [spatie/array-to-xml#181]
Hi, I tried to create array element in namespace

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$data = [
    'ns2:code' => ['1', '2', '3'],
];

$root = [
    'rootElementName' => 'root',
    '_attributes' => [
        'xmlns:ns2' => 'https://github.com/spatie/array-to-xml',
    ],
];

$xml = Spatie\ArrayToXml\ArrayToXml::convert($data, $root);
var_dump($xml);
```

which throws

**PHP Fatal error:  Uncaught DOMException: Namespace Error**

Problem is caused by [new DOMElement](https://github.com/spatie/array-to-xml/blob/418f1d4e321a37b711ac7d242c49b9de74f0aa82/src/ArrayToXml.php#L219).

Newly created DOMElement does not have namespace settings.

It could be easily fixed with 

```
//$child = new DOMElement($element->tagName); // replace with next line
$child = $this->document->createElement($element->tagName);

```

**Comment by freekmurze** [comment]
Feel free to PR a fix for this. Could you also add a test that would fail if not for the fix?

**Comment by vaclavvanik** [comment]
@freekmurze PR created :-)

**Comment by freekmurze** [comment]
Thanks!
