### ISSUE TITLE
value contianing speciachars must esacped 

### ISSUE THREAD

**Issue by bioshock** [spatie/array-to-xml#2]
<?php 
```
$array =  ['name'=>'this & that'] ; 
\Spatie\ArrayToXml\ArrayToXml::convert($array)
```
triggers  Warning: Spatie\ArrayToXml\ArrayToXml::convertElement(): unterminated entity reference 

to solve this value must be escaped properly  ie. using htmlspecialchars .or createTextNode method can be used

**Comment by freekmurze** [comment]
This is fixed in version 1.0.3
