### ISSUE TITLE
2.5.0 install all dev packages

### ISSUE THREAD

**Issue by diversen** [spatie/array-to-xml#33]
Just want to let you know that the latest release 2.5.0 installs  a lot of dev packages.

**Comment by freekmurze** [comment]
Current `composer.json` looks fine to me: https://github.com/spatie/array-to-xml/blob/784f24a/composer.json#L20

Reopen this issue if you can give a more detailed description of the problem, or even better, PR a fix with the problems you see.

**Comment by diversen** [comment]
I think it will resolve with the next release, as the 2.5.0 has 'spatie/phpunit-snapshot-assertions'  in the require section, whereas the master has this dependency in the 'require-dev' section.

**Comment by freekmurze** [comment]
You're right. I'll tag a new release now to avoid the snapshot package being pulled in.

Thanks for bringing this to my attention.

**Comment by diversen** [comment]
Thank you 👍
