### ISSUE TITLE
What about key that has an attribute but only has 1 string value?

### ISSUE THREAD

**Issue by ecasanes** [spatie/array-to-xml#34]
eg. 

`<CustomField name="ID">12345</CustomField>`

in the example, you can only generate

```
<CustomField attr1="value">
     <value>12345</value>
</CustomField>
```

**Comment by freekmurze** [comment]
Could you give an example of how you would like it to work? An example with an array an expected output and current output would be nice.

**Comment by ecasanes** [comment]
Thanks for the quick response.

As per my suggestion it would be good if from this array

```
[
 'CustomField' => [
  '_attributes' => ['name' => 'ID'],
  '%' => '12345'
 ]
]
```

it will produce this output

`<CustomField name="ID">12345</CustomField>`

**Comment by freekmurze** [comment]
I'd accept a non-breaking fully tested PR that adds this to the package.

**Comment by PetzJohannes** [comment]
`@value` or `_value` will do exactly the trick.

```
[
 'CustomField' => [
  '_attributes' => ['name' => 'ID'],
  '_value' => '12345'
 ]
]
```
Will give the output:
`<CustomField name="ID">12345</CustomField>`

Maybe you can describe this feature in the documentation.
