### ISSUE TITLE
Sequential arrays support (XML records list with the same key)

### ISSUE THREAD

**Issue by vedmant** [spatie/array-to-xml#61]
For example I have an array like:

    $data = [
        [
            'id' => 1,
            'name' => 'some name',
        ],
        [
            'id' => 2,
            'name' => 'some name 2',
        ],
    ];

And I want to get XML like this:

    <table>
      <record>
        <id>1</id>
        <name>some name</name>
      </record>
      <record>
        <id>2</id>
        <name>some name 2</name>
      </record>
    </table>

Currently this lib doesn't support sequential arrays, but it would be nice to pass an additional option to specify key name for sequential arrays. Something like this:

    ArrayToXml::convert($data, [
        'rootElementName' => 'table',
        'sequentialArrayElementsName' => 'record',
    ]);

Thanks!

**Comment by freekmurze** [comment]
Feel free to send a PR with tests.

**Comment by vedmant** [comment]
It actually works perfectly already, but there is no example for this in readme. It just needs to be a subarray with a key:

    $data = [
        'record' => [
            [
                'id' => 1,
                'name' => 'some name',
            ],
            [
                'id' => 2,
                'name' => 'some name 2',
            ],
        ],
    ];
