### ISSUE TITLE
Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by orlybg** [spatie/array-to-xml#7]
Locally the library works well, but in our live servers, we get this error

Fatal error: Class 'DOMDocument' not found in ../ArrayToXml.php on line 36

We have PHP 5.4.36 and libxml2 Version => 2.7.6

At first I thought we were lacking php-xml extensions, but seems it's not the case, any clue?

**Comment by freekmurze** [comment]
I haven't run in to this problem myself, so I can't give you a hint :-/ . It seems that there are some differences between your local and production environment.

If you find the solution, be sure to post it here for people who might have the some problem in the future.
