### ISSUE TITLE
UTF-8 Encoding

### ISSUE THREAD

**Issue by alexlauzon** [spatie/array-to-xml#70]
The output begins with <?xml version="1.0"?> but I really need to use this:
<?xml version="1.0" encoding="UTF-8"?>

For the moment, i'm fixing this by doing a str_replace on the $result.

**Comment by freekmurze** [comment]
Please open a new issue with a clear description of the problem.

**Comment by alexlauzon** [comment]
Oups. Sorry, forgot to format the code. I updated my comment. Thanks!

**Comment by antonioreyna** [comment]
same problem here how to add `encoding="UTF-8"` to the resulting xml string?
