### ISSUE TITLE
is it possible to set DOCTYPE

### ISSUE THREAD

**Issue by richayles** [spatie/array-to-xml#72]
Looking at the code it doesn't look like this is currently integrated - is this something that might come available on future versions?

**Comment by freekmurze** [comment]
Currently this is not supported. Feel free to send a PR.

**Comment by mtilokani** [comment]
@freekmurze Hi, is it now supported for DOCTYPE?

**Comment by richayles** [comment]
I did start this - https://github.com/spatie/array-to-xml/pull/73 but never completed, not sure if anyone else has taken this on since
