### ISSUE TITLE
Adding attribute to tag with simple value

### ISSUE THREAD

**Issue by dominikhalvonik** [spatie/array-to-xml#75]
Hi,
I tried to create simple XML, something like this:

`<Value Currency="GBP">200</Value>`

But I cannot found a way how to do it. I tried something like this:

`$package[0]['Value'] = 200;
$package[0]['Value']['_attributes'] = ['Currency' => 'GBP'];`

But the value of key Value did not changed. When I tried:

`$package[0]['Value'] = ['_attributes' => ['Currency' => 'GBP'], 200];`

I received an error.

 Thank you

**Comment by rappasoft** [comment]
`'Value' => ['_attributes' => ['Currency' => 'GBP'], '_value' => 200]`

**Comment by dominikhalvonik** [comment]
Hi @rappasoft ,

first of all thank you very much for your answer. But I tried that as one of the first solutions but that is not working for me. The response from that type of code is:

`<Value Currency="GBP">
    <_value>200</_value>
</Value>`

And that cannot be.

Thank you

**Comment by rappasoft** [comment]
I'm using the latest version:

 I have this: 

`'SourceSystem' => ['_attributes' => ['tc' => 999], '_value' => 'Source System'],`

And the output is this:

<img width="406" alt="screen shot 2018-08-03 at 10 57 43" src="https://user-images.githubusercontent.com/6026504/43649789-130e5b3c-970c-11e8-913d-82ad94273054.png">

**Comment by monmonja** [comment]
the _value has is_string on the source code, try
'Value' => ['_attributes' => ['Currency' => 'GBP'], '_value' => 200]
or 
['Value' => ['_attributes' => ['Currency' => 'GBP'], '_value' => strval(200)]]

**Comment by mmckalan** [comment]
Can anybody please explain why the is_string() is placed there?
Makes no sense to me.

**Comment by nmagu** [comment]
> 'SourceSystem' => ['_attributes' => ['tc' => 999], '_value' => 'Source System'],

Hello, I am getting a different output

**Comment by hesselkramer** [comment]
It would be nice to can assign a array to value because in some cases you will need this..

**Comment by hesselkramer** [comment]
You can bypass this by removing the _value like this:

I changed this :

    'The survivor' => [
        '_attributes' => ['house'=>'Hogwarts'],
        '_value' => 'Harry Potter'
    ]


To this:


    'The survivor' => [
        '_attributes' => ['house'=>'Hogwarts'],
          'Professor' => [
                 'Dumbledore' => '150'
                              ]
          ]
