### ISSUE TITLE
Code does not support multi dimensional array 

### ISSUE THREAD

**Issue by pratik-joshi-cactus** [spatie/array-to-xml#77]
```
            $arrKeywords = [];
            foreach($keywords as $keyword) {
                $arrKeywords[] =  ['kwd' =>  $keyword];
            }
            $this->kwd = $arrKeywords;
            $this->jatsArrayGenerated['front']['article-meta']['kwd-group'] = [
                '_attributes' => ['kwd-group-type' => 'Keywords'],
                '_value' => $this->kwd
            ];
```
However its showing me unnecessary _value tag
   ```
         <kwd-group kwd-group-type="Keywords">
                <_value>
                    <kwd>kw1</kwd>
                </_value>
                <_value>
                    <kwd>kw2</kwd>
                </_value>
            </kwd-group>

```
May I know what needs to be done? Thanks!

**Comment by amenk** [comment]
Have the same problem

**Comment by amenk** [comment]
"street" => [
                    "Somewhere",
                    "Address 2 "
                ],

should become

            <street>
                <line>Somewhere</line>
                <line>Somewhere</line>
                <line>Address 2</line>
            </street>

**Comment by freekmurze** [comment]
Feel free to submit a non-breaking, fully tested and documented PR that adds this.

**Comment by amenk** [comment]
Three wishes the same time (*German Kinderüberraschungs-Jingle in my head*) :rofl: 

Okay, I guess we need to make a config option for this then, right? Otherwise it would be a breaking change?

**Comment by pratik-joshi-cactus** [comment]
I used this and works like a charm :) 

```
            $this->jatsArrayGenerated['front']['article-meta']['kwd-group'] = [
                '_attributes' => ['kwd-group-type' => 'Keywords'],
                'kwd' => $arrKeywords
            ];

```

**Comment by JulioWar** [comment]
Hello, **I think I figured it out**. 

Instead of this:
```
"street" => [
       "Somewhere",
       "Address 2 "
]
```
Try something like this: 

```
"street" => [
       [ "Somewhere"],
       ["Address 2 "]
],
```

That should create this xml:

```
<street>
       <line>Somewhere</line>
       <line>Address 2</line>
</street>
```
