### ISSUE TITLE
Root element with namespace

### ISSUE THREAD

**Issue by jhourlad** [spatie/array-to-xml#80]
Setting the root element to something like:
`ApolloDataSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance`

triggers:
`Invalid Character Error`

Code:
`$response = ArrayToXml::convert($data, 'ApolloDataSet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ', false);`

![error](https://user-images.githubusercontent.com/3771945/46645484-a4d9f000-cbb7-11e8-943f-c305d0ea032b.png)

**Comment by freekmurze** [comment]
Could you PR a failing test for this?

**Comment by jhourlad** [comment]
@freekmurze Any reason for closing?
