### ISSUE TITLE
Invalid Character Error

### ISSUE THREAD

**Issue by richaInfowind** [spatie/array-to-xml#88]
Hello,

I am trying to convert this to xml and get Invalid Character Error:

On this File "D:\xampp\htdocs\sitemap\vendor\spatie\array-to-xml\src\ArrayToXml.php"

Array(
      [16] => Array
        (
            [parent] => aaa
            [numLinks] => 3
            [child] => Array
                (
                    [16] => Array
                        (
                            [parent] => abc
                            [numLinks] => 3
                        )
                )
        )

[17] => Array
        (
            [parent] =>bb
            [numLinks] => 3
            [child] => Array
                (
                    [16] => Array
                        (
                            [parent] => abb
                            [numLinks] => 3
                            [child] => Array
                                (
                                    [16] => Array
                                        (
                                            [parent] => abc
                                            [numLinks] => 3
                                        )
                                )
                        )

                    [17] => Array
                        (
                            [parent] => acb
                            [numLinks] => 3
                        )
                )
        )
)

**Comment by rekliner** [comment]
I was getting the same and it turns out this doesn't support having numerically indexed root elements.  You'll have to wrap your array with another name-indexed array.  Ex. Rather than convert($links) you'll need $wrapped_links["Links"] = $links; then convert($wrapped_links);

@spatie it would be nice if you could work in support of numerically indexed arrays.

**Comment by PeekLeon** [comment]
Hello,
I have the same problem as you.
To work around this error I put my key as an attribute or I create a new entry.

foreach ($aReturn as $key=> $value) {
    $aReturn[$key]['id']=$key; // Create new entry id with value (<id>myKey</id>)
    $aReturn[$key]['_attributes']['id']=$key; // I put a software attribute with my key (id=myKey)
}
$aReturnXml['software'] = $aReturn;

**Comment by freekmurze** [comment]
Numeric keys will be added via #88 soon.
