### ISSUE TITLE
How to add child tags to an existing xml file

### ISSUE THREAD

**Issue by dieppham2016** [spatie/array-to-xml#93]
How to add child tags to an existing xml file?
-------------------
Example:
----------
```
<?xml version="1.0"?>
<root>
    <tag_one></tag_one>
</root>
```

-------------------
##### How to add` <tag_two></tag_two>` append `<tag_one></tag_one>`
--------------
Thanks.``

**Comment by PeekLeon** [comment]
Hi,

Normaly you have an array like this :

$array['tag_one']="foo";

for adding an element at 'tag_one':

$array['tag_one']['tag_two']="foo";

Result:

```xml
<?xml version="1.0"?>
<root>
    <tag_one>
        <tag_two>foo</tag_two>
    </tag_one>
</root>
```

**Comment by dieppham2016** [comment]
ok, thanks you!
